name: deploy
on:
  push:
    branches:
      - rtd

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          pip install -r doc/requirements.txt

      - name: Clone
        run: |
          git clone https://github.com/sphinx-locales/sphinx-intl.git draft

      - name: Build the book
        run: |
          cd doc
          sphinx-build -D language=zh_CN -b html ./ _build/html

      - name: GitHub Pages action
        uses: peaceiris/actions-gh-pages@v3.6.1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: doc/_build/html
